### ISSUE TITLE
Some test results using shadow images with mask

### ISSUE THREAD

**Issue by mychina75** [IsHYuhi/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks#13]
Hi, thank you for your work.
I tested pretrained G2 model with some shadow image, together with masks. 
here are some results, any idea of getting improvements? 

thank you.

![grid_SBU-test34](https://user-images.githubusercontent.com/798230/94120381-9fe4d880-fe82-11ea-9761-7237f229e8bd.jpg)
![grid_SBU-test33](https://user-images.githubusercontent.com/798230/94120397-a3785f80-fe82-11ea-8af7-b0a7f32d0caa.jpg)
![grid_SBU-test29](https://user-images.githubusercontent.com/798230/94120447-b1c67b80-fe82-11ea-988c-4eaf39579228.jpg)
![grid_SBU-test22](https://user-images.githubusercontent.com/798230/94120477-bbe87a00-fe82-11ea-9c32-e15fe9fce213.jpg)

**Comment by IsHYuhi** [comment]
I apologize for the long delay in replying.
The module is not implemented in this code, but you need to observe the metrics or loss for validation data and save the model. 
Please reopen this issue if you have any problems.

Thank you.
