### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Joge-jiaye** [IsHYuhi/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks#15]
XIO:  fatal IO error 0 (Success) on X server "localhost:19.0"
      after 6943 requests (6943 known processed) with 8 events remaining.
请问这个问题怎么解决
我实在服务器上跑的，然后每次自己电脑断网后就会出现这个问题

**Comment by IsHYuhi** [comment]
I apologize for the long delay in replying.
I'm sorry, but I don't know how to deal with that problem.
Please let me know if there are any other problems.

**Comment by yuanyufang** [comment]
> XIO: fatal IO error 0 (Success) on X server "localhost:19.0" after 6943 requests (6943 known processed) with 8 events remaining. 请问这个问题怎么解决 我实在服务器上跑的，然后每次自己电脑断网后就会出现这个问题
Hello, may I ask whether the code you downloaded can be run directly? Why the loss is 0 when I run it? May I ask whether the code needs to be adjusted

**Comment by yuanyufang** [comment]
> XIO: fatal IO error 0 (Success) on X server "localhost:19.0" after 6943 requests (6943 known processed) with 8 events remaining. 请问这个问题怎么解决 我实在服务器上跑的，然后每次自己电脑断网后就会出现这个问题

你好，请问你下载的这个代码能直接运行吗，为什么我运行显示损失为0，请问需要调整代码吗
