### ISSUE TITLE
Stacked Conditional Generative Adversarial Networks for Jointly Learning Shadow Detection and Shadow Remova

### ISSUE THREAD

**Issue by yuanyufang** [IsHYuhi/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks#16]
hello
Stacked Conditional Generative Adversarial Networks for Jointly Learning Shadow Detection and Shadow Remova，
Why does this code you shared run with zero loss
Thank you for your answer

**Comment by IsHYuhi** [comment]
I’m sorry for the delayed response.

Can you give us some more details about the situation?
If you are still having problems, please open this issue again.

Thanks.
