### ISSUE TITLE
about detach() in 220th and 228th line

### ISSUE THREAD

**Issue by Leixiujie** [IsHYuhi/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks#17]
In the usage phase of the discriminators, shall we use the detach() in our model?  Whether it makes the GAN lose its function?

**Comment by IsHYuhi** [comment]
I’m sorry for the delayed response.

Can you give me some more details about the situation?
If you are still having problems, please open this issue again.

Thanks.
