### ISSUE TITLE
evaluation code for BER and RMSE

### ISSUE THREAD

**Issue by xuhangc** [IsHYuhi/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks#18]
Appreciate your nice work.
Can you release the evaluation code for BER and RMSE so that we can evaluate locally.

**Comment by IsHYuhi** [comment]
I’m sorry for the delayed response.
I didn't implement the evaluation code. So, you need to contact the author.

https://github.com/DeepInsight-PCALab/ST-CGAN/issues/6#issuecomment-439057423

Thanks.
