### ISSUE TITLE
Training on my dataset

### ISSUE THREAD

**Issue by Hamzat0014** [IsHYuhi/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks#19]
I am trying to train your model on my dataset.
My dataset consist of RGB shaow, shadowfree and shadow mask images. All images have 3 channels.

I am facing this issue:
**"RuntimeError: Given groups=1, weight of size [64, 4, 4, 4], expected input[2, 6, 256, 256] to have 4 channels, but got 6 channels instead"**

can you please guide me how to proceed further, will be much thankful to you.

**Comment by IsHYuhi** [comment]
I’m sorry for the delayed response.
You need to change" in_channels" 9 of the models.

If you still have problems, please re-open the issue.

Thanks.

**Comment by hidataset890** [comment]
> 

Hello, now the pre-training model is invalid, can you send it to me? be deeply grateful

**Comment by hidataset890** [comment]
> I am trying to train your model on my dataset. My dataset consist of RGB shaow, shadowfree and shadow mask images. All images have 3 channels.
> 
> I am facing this issue: **"RuntimeError: Given groups=1, weight of size [64, 4, 4, 4], expected input[2, 6, 256, 256] to have 4 channels, but got 6 channels instead"**
> 
> can you please guide me how to proceed further, will be much thankful to you.
Hello, now the pre-training model is invalid, can you send it to me? be deeply grateful

**Comment by Hamzat0014** [comment]
> > 
> 
> Hello, now the pre-training model is invalid, can you send it to me? be deeply grateful

@hidataset890 i have the checkpoints downloaded of pre-trained model.

**Comment by Hamzat0014** [comment]
> I’m sorry for the delayed response. You need to change" in_channels" 9 of the models.
> 
> If you still have problems, please re-open the issue.
> 
> Thanks.

@IsHYuhi  i am still facing the same issue. 

My point is that if the images shape, data type etc if all are same as of the istd, data set than why the issue is arising?

**Comment by hidataset890** [comment]
> > > 
> > 
> > 
> > 你好，现在前期培训模型无效，可以发给我吗？深表感激
> 
> @hidataset890我已经下载了预训练模型的检查点。

my mailbox：ca13615693369@163.com    can you send pre-trained model to me? be deeply grateful

**Comment by Hamzat0014** [comment]
> 

please check your email

**Comment by hidataset890** [comment]
> > 
> 
> please check your email

1224214681@qq.com  is qq email   please try it,thanks

**Comment by Hamzat0014** [comment]
> I’m sorry for the delayed response. You need to change" in_channels" 9 of the models.
> 
> If you still have problems, please re-open the issue.
> 
> Thanks.

Hello

Hope you are well.
There was an issue in data_loader.py and ISTD_transform.py, the model was taking 3 channels for train_B, while the model was designed to take only 1 channel.
so by adding following line of code in data_loader.py the issue was resolved:

gt_shadow=gt_shadow[:1]
