### ISSUE TITLE
TypeError: conv_transpose2d(): argument 'output_padding' (position 6) must be tuple of ints, not tuple

### ISSUE THREAD

**Issue by ryan3507** [IsHYuhi/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks#21]
Hi I am receiving this error when trying to run this code on Pytorch. 
File "/content/gdrive/MyDrive/CAT_Vehicle/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks/models/ST_CGAN.py", line 131, in forward
    x6 = self.CvT6(x5)
File "/content/gdrive/MyDrive/CAT_Vehicle/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks/models/ST_CGAN.py", line 84, in forward
    x = self.conv(x)
TypeError: conv_transpose2d(): argument 'output_padding' (position 6) must be tuple of ints, not tuple
Thank you so much!

**Comment by justperson94** [comment]
In my case, using pytorch 1.2.0 solved this problem
Try change your version of pytorch

**Comment by mareksmarkans** [comment]
In models/ST_CGAN.py there is a problem with positional arguments at line 97 when function nn.ConvTranspose2d is called. If you change that line to:
```
self.conv = nn.ConvTranspose2d(
            in_channels, out_channels, kernel_size, stride, padding, bias=bias
        )
```
the code works.

**Comment by IsHYuhi** [comment]
@mareksmarkans 
I appreciate your help!
