### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by mychina75** [IsHYuhi/ST-CGAN_Stacked_Conditional_Generative_Adversarial_Networks#9]
Hi, 
Thank you for your work.
Would you please provide the pretrained model?

thanks a lot~

**Comment by IsHYuhi** [comment]
Hi, @mychina75 .
I'm going to add the trained model tomorrow.
So, could you wait for a day or so?

Thank you.

**Comment by IsHYuhi** [comment]
Hi, @mychina75 .
I added trained weight. #12 
If any other problem or question, please do not hesitate to ask me.
Thank you.
